# Generated by Django 5.2.10 on 2026-01-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0011_remove_message_receiver_message_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='conversation_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_id',
        ),
    ]
