# Generated by Django 5.2.10 on 2026-01-14 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0012_rename_conversation_message_conversation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations_Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatApp.conversations')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatApp.user')),
            ],
        ),
    ]
