# Generated by Django 5.2.10 on 2026-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0013_conversations_users'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversations_users',
            constraint=models.UniqueConstraint(fields=('conversation_id', 'user_id'), name='unique_user_in_conversation'),
        ),
    ]
