# Generated by Django 5.2.10 on 2026-01-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0014_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations_users',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
