# Generated by Django 5.2.10 on 2026-02-02 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0016_message_is_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Conversations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatApp.user')),
            ],
        ),
    ]
